# Generated by Django 4.1.4 on 2022-12-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentDetails",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("f_name", models.CharField(max_length=20)),
                ("l_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=20)),
                ("mobile_no", models.IntegerField()),
            ],
        ),
    ]
